### ISSUE TITLE
[Question]: Use `Directory.Packages.props` to import Krypton Toolkit packages

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Extended-Toolkit#192]
Shouldn't we use `Directory.Packages.props` to import the standard toolkit packages to make the `csproj` files cleaner?

**Comment by Smurf-IV** [comment]
The current pattern works, and allows extra (specific versions) dll's to also work.
But if the `Directory.Packages.props` also solves the `Designer / toolbox` issues, then go ahead and give it a try.

**Comment by Wagnerp** [comment]
I've got it working on the `version-next-outlook-grid` branch, **but** it appears that you need to add other packages that the toolkit uses to this file, as the `ManagePackageVersionsCentrally` variable is needed. I don't know if you can select specific projects to have specific packages yet.

**Comment by Wagnerp** [comment]
Might be a bit hacky, but I wonder if we could put a `Directory.Packages.props` file in the directories that a specific package is needed?

**Comment by Smurf-IV** [comment]
eek.. seems like a hack to solve a problem that is already solved with the project template that is in use.

**Comment by Wagnerp** [comment]
There is another issue (unrelated) to this one. The build scripts does not currently generate NuGet packages. It can be done via `csproj` but I don't know if by doing this full & lite packages will be generated?
