### ISSUE TITLE
OutlookGrid Column right click causes error 

### ISSUE THREAD

**Issue by dax-leo** [Krypton-Suite/Extended-Toolkit#21]
Hi,

Looks like you have bug in Outlook Grid component.
Right click on column header will cause the following error:

`{"Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure \"KryptonOutlookGrid.Utilities.Language.EnglishStringsGB.resources\" was correctly embedded or linked into assembly \"Krypton.Toolkit.Suite.Extended.Outlook.Grid\" at compile time, or that all the satellite assemblies required are loadable and fully signed."}`

Looks like changing : 
`           
resourceManagerUS = new ResourceManager("KryptonOutlookGrid.Utilities.Language.EnglishStringsUS", Assembly.GetExecutingAssembly());
resourceManagerGB = new ResourceManager("KryptonOutlookGrid.Utilities.Language.EnglishStringsGB", Assembly.GetExecutingAssembly());            
`

into :
`            resourceManagerUS = new ResourceManager("Krypton.Toolkit.Suite.Extended.Outlook.Grid.Utilities.Language.EnglishStringsUS", Assembly.GetExecutingAssembly());
            resourceManagerGB = new ResourceManager("Krypton.Toolkit.Suite.Extended.Outlook.Grid.Utilities.Language.EnglishStringsGB", Assembly.GetExecutingAssembly());
`

in Krypton.Toolkit.Suite.Extended.Outlook.Grid.LanguageManager class initialization method should solve the issue.
I guess you made some changes to namespaces recently, maybe checking for "namespace orphans" in some text fields should be recommended.

Regards,
Darko

**Comment by Wagnerp** [comment]
Hi @dax-leo 

Thanks for reporting! I'll have a look into the issue.
