### ISSUE TITLE
[Bug]: Nameof `TreeGridView` workspace needs sorting

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Extended-Toolkit#210]
**Describe the bug**
`namespace Krypton.Toolkit.Suite.Extended.Tree.Grid.View`

Should be 

`namespace Krypton.Toolkit.Suite.Extended.TreeGridView`

**Comment by Smurf-IV** [comment]
Also.. 
What does this do:

![image](https://user-images.githubusercontent.com/2418812/124779168-75f43280-df39-11eb-81df-87abfb4a3e2d.png)


i.e delete this class

**Comment by Smurf-IV** [comment]
I am currently trying to use this class, So will update all changes once I have completed "Success / or Failure"

@Wagnerp Do you have any examples on how it was intended to be used ?

**Comment by Wagnerp** [comment]
That originated from [here](https://github.com/Krypton-Suite-Legacy-Archive/Krypton-Toolkit-Suite-Extended-NET-5.470/tree/master/Source/Krypton%20Toolkit%20Suite%20Extended/Full%20Toolkit/Extended%20Controls/ExtendedToolkit/Controls/TreeGridView), which originated from [here](https://github.com/ncarp/ExtendedRenderer/tree/master/TreeGridView). I don't remember if it was fully implemented in the original project.

**Comment by Smurf-IV** [comment]
Add code fixes from here:
- https://docs.microsoft.com/en-us/archive/blogs/markrideout/customizing-the-datagridview-to-support-expandingcollapsing-ala-treegridview
-
