### ISSUE TITLE
[Bug]: `ObjectListView` is covered by GPL, so "Can / Should" not be included in this code suite

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Extended-Toolkit#213]
**Describe the bug**
As above

**To Reproduce**
This project is covered by BSD - 3 Clause, so ObjectListView cannot be included because that means anyone using this will also need to to expose their code as well.

**Comment by Wagnerp** [comment]
I thought that I had removed the files, is this not the case on some branches?

**Comment by Smurf-IV** [comment]
I must have seen it on a "stale" branch.
