### ISSUE TITLE
[Bug]: Lite versions do not support `netcoreapp3.1`

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Extended-Toolkit#222]
**Describe the bug**
As title states

**Comment by Wagnerp** [comment]
Fixed

**Comment by Smurf-IV** [comment]
Please update the Nuget Description for the LKte Package
Please update documentation about the Lite Package
Do the Same for the Standard Toolkit.

**Comment by Wagnerp** [comment]
Fully implemented
