### ISSUE TITLE
[Bug]: Button text is not changeable

### ISSUE THREAD

**Issue by W4TR1X** [Krypton-Suite/Extended-Toolkit#242]
**Describe the bug**
Krypton Button Text value is not changing. I think Persistent Text property is overriding the Text property.

**To Reproduce**
Add a button to a form,
Try changing it is Text property

**Expected behavior**
Text change according to input value :)

**Screenshots**
![image](https://user-images.githubusercontent.com/30633382/130022961-ac00d8b9-23c0-4116-bbdc-73e9ea3d18f7.png)

**Desktop (please complete the following information):**
 - Package referances: Krypton.Toolkit.Suite.Extended.*.Lite version 6.0.2108

**Comment by Wagnerp** [comment]
@W4TR1X 

Please update to `6.2108.1`, as a fix has already been issued

**Comment by W4TR1X** [comment]
Sorry for the duplication. Thanks.
