### ISSUE TITLE
[Bug]: 2108 Canary Nuget has missing Icons

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Extended-Toolkit#244]
![image](https://user-images.githubusercontent.com/2418812/130667299-bfd51f62-cac3-43a3-b71d-a5f379d89536.png)

**Comment by Wagnerp** [comment]
Now that there is a reduction in frameworks, `Lite` packages are no longer needed

**Comment by Smurf-IV** [comment]
Agreed, but the others for 2108 are missing as well.

**Comment by Wagnerp** [comment]
> Agreed, but the others for 2108 are missing as well.

Are they green? If so, I did make a mistake back in July whilst uploading. Will be rectified in 2109. :)
