### ISSUE TITLE
[Feature Request]: Adapt `sln` file to behave more like the ST demos

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Extended-Toolkit#246]
**Is your feature request related to a problem? Please describe.**
Have 'Dev' & 'NuGet' options

**Comment by Wagnerp** [comment]
@Smurf-IV How did you link the toolkit together?

**Comment by Smurf-IV** [comment]
Not sure I understand the question..

**Comment by Wagnerp** [comment]
Think I've got it, I set the wrong paths

**Comment by Wagnerp** [comment]
I wonder if it can be done with canary/stable?

**Comment by Smurf-IV** [comment]
> I wonder if it can be done with canary/stable?

It will be done when all this is merged into those branches ;-)

**Comment by Wagnerp** [comment]
Won't work, based on the solution type
