### ISSUE TITLE
[Bug]: Krypton.Toolkit.Suite.Extended.* v.6.2110.274-beta Nuget package install error

### ISSUE THREAD

**Issue by W4TR1X** [Krypton-Suite/Extended-Toolkit#260]
**Describe the bug**
Krypton.Toolkit.Suite.Extended.* v. 6.2110.274-beta not installable via nuget. 
Only Krypton.Toolkit.Suite.Extended.Core.Canary v.6.2110.274-beta is installable.

Error code: NU1101 
Error message: Unable to find package **`Krypton.Toolkit.Suite.Extended.Tools`**. No packages exist with this id in source(s): nuget.org

**To Reproduce**
1. Create fresh project
2. Try to add nuget package

**Expected behavior**
Adding nuget successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/30633382/140986005-68e27259-e586-42d0-8b2d-097fdb834e3b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS: 2022 Preview

**Additional context**
I apologize in advance if I missed something.

**Comment by Wagnerp** [comment]
Hi @W4TR1X Is this working now?

**Comment by W4TR1X** [comment]
Currently works as expected

6.22.1.8-beta
![image](https://user-images.githubusercontent.com/30633382/149634181-46bddc84-a498-485a-b1b3-3bd906f961f6.png)

60.22.1.12-beta
![image](https://user-images.githubusercontent.com/30633382/149634202-314d0224-adb4-4ad2-a692-5c4173bb2386.png)

**Comment by Wagnerp** [comment]
Hi @W4TR1X great to hear. Can I close this now?

**Comment by W4TR1X** [comment]
Yes. Ofcourse.
