### ISSUE TITLE
[Bug]: Crashes using Outlook Grid control

### ISSUE THREAD

**Issue by NintendoPlayer** [Krypton-Suite/Extended-Toolkit#268]
**Describe the bug**
I have an app that uses Krypton standard toolkit and the outlook grid from the extended toolkit.  I have updated every project from the solution to 4.8 framework.  The standard toolkit is on 6.2111.312 version and the outlook grid nuger is on 5.550.2106.  After fixing some errors with all these updates, the app crashes on launch

**To Reproduce**
I launch my app and it crashes on this line:

`this.kryptonOutlookGridGroupBox1 = new Krypton.Toolkit.Suite.Extended.Outlook.Grid.KryptonOutlookGridGroupBox();`

The error is:

`System.Resources.MissingManifestResourceException: 'No se encontraron recursos adecuados para la referencia cultural especificada o para la referencia cultural neutra. Compruebe si "Krypton.Toolkit.Suite.Extended.Outlook.Grid.Utilities.Language.Strings.resources" se ha incrustado o vinculado  correctamente en el ensamblado "Krypton.Toolkit.Suite.Extended.Outlook.Grid" durante el tiempo de compilación o que todos los ensamblados satélite requeridos pueden cargarse y están completamente firmados.'
`
I'm not translating it because I don't know how Visual Studio states this in english

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Visual Studio 2019, fully updated

Some help is appreciated, thank you!

**Comment by Smurf-IV** [comment]
> The standard toolkit is on 6.2111.312 version and the outlook grid nuger is on 5.550.2106

These will not be compatible until either
- outlook grid nuget is of the same version (`6.2111.312`)
- Build outlook grid yourself and change the linked standard toolkit to use `6.2111.312`

**Comment by Wagnerp** [comment]
@NintendoPlayer & @Smurf-IV I'm hopefully going to build a new canary/stable release soon. **_BUT_** I need to fix some build bugs first.

**Comment by NintendoPlayer** [comment]
@Smurf-IV  & @Wagnerp  thank you for helping!  I thought the versions where the issue, but I thought the last version of each suit would be compatible.  I'll try some of the suggestions or wait.
Thanks!!

**Comment by Wagnerp** [comment]
@NintendoPlayer A new build has been released with the latest canary version of the standard toolkit.

**Comment by NintendoPlayer** [comment]
> @NintendoPlayer A new build has been released with the latest canary version of the standard toolkit.

I've changed the standard toolkit and outlook grid packages to the canary release and now it shows a slightly different error:

`System.Resources.MissingManifestResourceException: 'No se encontraron recursos adecuados para la referencia cultural especificada o para la referencia cultural neutra. Compruebe si "Krypton.Toolkit.Suite.Extended.Outlook.Grid.Language.Strings.en-US.resources" se ha incrustado o vinculado  correctamente en el ensamblado "Krypton.Toolkit.Suite.Extended.Outlook.Grid" durante el tiempo de compilación o que todos los ensamblados satélite requeridos pueden cargarse y están completamente firmados.'
`

**Comment by Wagnerp** [comment]
> > @NintendoPlayer A new build has been released with the latest canary version of the standard toolkit.
> 
> I've changed the standard toolkit and outlook grid packages to the canary release and now it shows a slightly different error:
> 
> `System.Resources.MissingManifestResourceException: 'No se encontraron recursos adecuados para la referencia cultural especificada o para la referencia cultural neutra. Compruebe si "Krypton.Toolkit.Suite.Extended.Outlook.Grid.Language.Strings.en-US.resources" se ha incrustado o vinculado correctamente en el ensamblado "Krypton.Toolkit.Suite.Extended.Outlook.Grid" durante el tiempo de compilación o que todos los ensamblados satélite requeridos pueden cargarse y están completamente firmados.' `

Is there a way to reproduce? Looks as if some resources are missing.

**Comment by NintendoPlayer** [comment]
> 

Sorry for the late reply, my bad!  I don't know, this issue has appeared after I have updated to krypton v6.XXXX.XXX.  Yes, is says that "No appropiate resources were found for the culture specified of the neutral one.  Check if (the resource name) is embebed or linked correctly to the assembly (krypton outlook grid)" during compile time".  So this resource should be inside the outlook grid library.  At least is in the source code.  I don't know if there is something that I have to change in the project or if something about the culture was changed on the library

**Comment by NintendoPlayer** [comment]
@Wagnerp Sorry but, could this be the issue?

The error is about a resource not embeded.  This line:

`rm = new ResourceManager("Krypton.Toolkit.Suite.Extended.Outlook.Grid.Language.Strings.en-US", Assembly.GetExecutingAssembly());`

is in the LanguageManager inside Utilities.  Maybe there is something wrong with the namespaces?  Because en-US.resx has this namespace:

`Krypton.Toolkit.Suite.Extended.Outlook.Grid.**Utilities**.Language.Strings`

Could this be the cause of the error?  Or is it just that I have no idea :D??

Thank you!

**Comment by Wagnerp** [comment]
> @Wagnerp Sorry but, could this be the issue?
> 
> The error is about a resource not embeded. This line:
> 
> `rm = new ResourceManager("Krypton.Toolkit.Suite.Extended.Outlook.Grid.Language.Strings.en-US", Assembly.GetExecutingAssembly());`
> 
> is in the LanguageManager inside Utilities. Maybe there is something wrong with the namespaces? Because en-US.resx has this namespace:
> 
> `Krypton.Toolkit.Suite.Extended.Outlook.Grid.**Utilities**.Language.Strings`
> 
> Could this be the cause of the error? Or is it just that I have no idea :D??
> 
> Thank you!

Yes it could be. I'll have a look later.

**Comment by Wagnerp** [comment]
Found the issue, a new version will be deployed shortly

**Comment by Wagnerp** [comment]
Fixed in build 2201. @NintendoPlayer Please reopen if necessary.

**Comment by NintendoPlayer** [comment]
Hi!  The standard toolkit has released the 2201revision on canary channel.  Could this also be done for the extended toolkit?  I can't run my project because of this bug.

Thanks for your hard work!

**Comment by Wagnerp** [comment]
Hi @NintendoPlayer 

Is there any way of rolling back on pre-2201.1? We're transitioning over to a new versioning scheme, which won't take effect until the next canary release.

**Comment by NintendoPlayer** [comment]
@Wagnerp  The problem is that the issue I need is on revision 2201, right?  So I need to use revision 2201, correct me if I'm wrong

**Comment by Wagnerp** [comment]
> @Wagnerp The problem is that the issue I need is on revision 2201, right? So I need to use revision 2201, correct me if I'm wrong

The extended toolkit will pull in the latest revision, i.e 2112.xxx. But it may not work with 2201.1 until it's been changed in the config files. A new canary build will be published, but it may take a few days, as changes made in `alpha` need to filter through.

**Comment by NintendoPlayer** [comment]
> > @Wagnerp The problem is that the issue I need is on revision 2201, right? So I need to use revision 2201, correct me if I'm wrong
> 
> The extended toolkit will pull in the latest revision, i.e 2112.xxx. But it may not work with 2201.1 until it's been changed in the config files. A new canary build will be published, but it may take a few days, as changes made in `alpha` need to filter through.

So I'll have to wait for 2201.1 revision.  I don't really know what was the last working version of the outlook grid.

**Comment by Wagnerp** [comment]
> > > @Wagnerp The problem is that the issue I need is on revision 2201, right? So I need to use revision 2201, correct me if I'm wrong
> > 
> > 
> > The extended toolkit will pull in the latest revision, i.e 2112.xxx. But it may not work with 2201.1 until it's been changed in the config files. A new canary build will be published, but it may take a few days, as changes made in `alpha` need to filter through.
> 
> So I'll have to wait for 2201.1 revision. I don't really know what was the last working version of the outlook grid.

@NintendoPlayer It'll be https://www.nuget.org/packages/Krypton.Toolkit.Canary/6.2112.355-beta, look out in the next few days with a version string similar to `6.22.1.x`.

**Comment by NintendoPlayer** [comment]
@Wagnerp Ok, I just did a search and found Krypton.Toolkit -> "Standard", Canary and Nightly.  Right now the nightly nuget has that version string.  But the stardard nuget has a higher version than canary builds.  Sorry, but, I'm pretty lost right now :D.  The problem is that older versions has the old naming space, so it's a mess to go back.

**Comment by Wagnerp** [comment]
> @Wagnerp Ok, I just did a search and found Krypton.Toolkit -> "Standard", Canary and Nightly. Right now the nightly nuget has that version string. But the stardard nuget has a higher version than canary builds. Sorry, but, I'm pretty lost right now :D. The problem is that older versions has the old naming space, so it's a mess to go back.

Hi @NintendoPlayer No problem, I'll be updating the Canary version within the next couple of days.

**Comment by NintendoPlayer** [comment]
> > @Wagnerp Ok, I just did a search and found Krypton.Toolkit -> "Standard", Canary and Nightly. Right now the nightly nuget has that version string. But the stardard nuget has a higher version than canary builds. Sorry, but, I'm pretty lost right now :D. The problem is that older versions has the old naming space, so it's a mess to go back.
> 
> Hi @NintendoPlayer No problem, I'll be updating the Canary version within the next couple of days.

@Wagnerp Ok, I'll wait then.  Thank you for the good work!!

**Comment by NintendoPlayer** [comment]
> > @Wagnerp Ok, I just did a search and found Krypton.Toolkit -> "Standard", Canary and Nightly. Right now the nightly nuget has that version string. But the stardard nuget has a higher version than canary builds. Sorry, but, I'm pretty lost right now :D. The problem is that older versions has the old naming space, so it's a mess to go back.
> 
> Hi @NintendoPlayer No problem, I'll be updating the Canary version within the next couple of days.

Hi @Wagnerp, sorry to bother again with this.  I updated the outlook.grid.canary package to version 60.22.1.12-beta.  The standard toolkit are all on the 6.2201.1-beta.  The issue remains.  Since the issue was on the extended toolkit and it has been updated to 6.22.1.x-beta versioning, shouldn't it solve the issue #268?

Thanks!

**Comment by Wagnerp** [comment]
Hi @NintendoPlayer Could you please test using the newly released nightly builds?

**Comment by NintendoPlayer** [comment]
Hi there @Wagnerp!  So I have installed Standart Toolkit to the last Canary version available and the nightly build of grid extension also to the last version available.  It just throws the same error:

`System.Resources.MissingManifestResourceException: 'No se encontraron recursos adecuados para la referencia cultural especificada o para la referencia cultural neutra. Compruebe si "Krypton.Toolkit.Suite.Extended.Outlook.Grid.Resources.Language.Strings.en-US.resources" se ha incrustado o vinculado  correctamente en el ensamblado "Krypton.Toolkit.Suite.Extended.Outlook.Grid" durante el tiempo de compilación o que todos los ensamblados satélite requeridos pueden cargarse y están completamente firmados.'`

I have the canary standard toolkit because the nightly build of outlook grid needs canary, I don't know if that is the wait it should be.

**Comment by NintendoPlayer** [comment]
Hi @Wagnerp , just for the record, I have installed nightly builds of standard and outlook grid packages, to version -17 beta and -18 beta respectively; the error persist.

**Comment by Wagnerp** [comment]
@NintendoPlayer Is this linked to #226?

**Comment by NintendoPlayer** [comment]
@Wagnerp  it could be, at least the message is almost identical to the first one:

`Message=Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Krypton.Toolkit.Suite.Extended.Outlook.Grid.Utilities.Language.Strings.resources" was correctly embedded or linked into assembly "Krypton.Toolkit.Suite.Extended.Outlook.Grid" at compile time, or that all the satellite assemblies required are loadable and fully signed`

The error I got since I updated outlook grid was:

`
System.Resources.MissingManifestResourceException: 'No se encontraron recursos adecuados para la referencia cultural especificada o para la referencia cultural neutra. Compruebe si "Krypton.Toolkit.Suite.Extended.Outlook.Grid.Resources.Language.Strings.en-US.resources" se ha incrustado o vinculado  correctamente en el ensamblado "Krypton.Toolkit.Suite.Extended.Outlook.Grid" durante el tiempo de compilación o que todos los ensamblados satélite requeridos pueden cargarse y están completamente firmados.`

So I think they are related yes

**Comment by Wagnerp** [comment]
Hi @NintendoPlayer I think I've found the bug... fixing today!

**Comment by Wagnerp** [comment]
Hi @NintendoPlayer before uploading, could you try this specific version please? https://1drv.ms/u/s!AnKzT7Em-ox5g-4GpKxCw72J7kMvYw?e=brvGAI

**Comment by Wagnerp** [comment]
> > Hi @NintendoPlayer before uploading, could you try this specific version please? https://1drv.ms/u/s!AnKzT7Em-ox5g-4GpKxCw72J7kMvYw?e=brvGAI
> 
> Great @Wagnerp!! That fixes the issue, the app is opening as usual. Thanks for this fix!
> 
> P.D: There are things that behave differently from the version I was using, but this is another story, I will test some things and the I will open another issue if needed.

@NintendoPlayer That's great to hear! A new nightly build with the fix will be out tomorrow, currently performing refactoring on the module.

**Comment by Wagnerp** [comment]
Fixed - 19/01/2022
