### ISSUE TITLE
[Feature Request]: NuGet Package Information needs to have direct download links

### ISSUE THREAD

**Issue by kumar007git** [Krypton-Suite/Extended-Toolkit#271]
Is there an easy way to download all the latest extended toolkit controls packages in one zip file or at least provide links to the latest version nuget packages to each of them just like how it is done for standard toolkit? Unlike the standard toolkit the links on the extended toolkit page do not open nuget package download page instead they open an image/icon file. Searching for the packages on shows 300 results which include old and new so that is not a good way to get the files.

Also, there is canary and stable version. What is the difference between them and which one should I use?

**Comment by Wagnerp** [comment]
Hi @kumar007git 

At the moment, no however as we prepare to release V6, a single zip file can be looked into, plus direct links to the latest packages. Hope this helps.

**Comment by kumar007git** [comment]
Needless to say, it is very confusing. I was an early user of Krypton toolkit and I wanted to use this new version but the confusion and difficulty in getting them is too high and I decided not to download them. I guess I'll wait until you release v6 in a single zip file.

Also, there is canary and stable version. What is the difference between them and which one should I use?

Thanks for maintaining and releasing this toolkit. Nice job!

**Comment by Wagnerp** [comment]
Hi @kumar007git 

The stable version is what you need if your deploying your app to the customer, if you're still developing your app, and want to try out the latest features, then use canary, but bear in mind that these are unstable. I see what you mean by direct links, I'll sort it out by January.

**Comment by Wagnerp** [comment]
Completed - 26/12/2021
