### ISSUE TITLE
[Feature Request]: `KryptonOutlookGridGroupBox` 'CreateGroupBox' method not found

### ISSUE THREAD

**Issue by NintendoPlayer** [Krypton-Suite/Extended-Toolkit#290]
Hi!

I've been using the original KrptonOutlookGrid library from JDH Software.  I have an additional method on this library, especifically on `KryptonOutlookGridGroupBox.cs`:

```cs    
        /// <summary>
        /// Handles the DragDrop event. Add a new grouping column following a drag drop from the grid
        /// </summary>
        /// <param name="column"></param>
        /// <param name="sender">Source of the event.</param>
        /// <param name="e">A DragEventArgs that contains the event data.</param>
        public void CreateGroupBox(DataGridViewColumn column, string groupingType, SortOrder Order, bool sortBySummary)
        {
            string columnToMove = column.Name;
            string columnName = column.Name;
            string columnText = column.HeaderText;
            SortOrder sortOrder;
            DataGridViewColumnSortMode sortMode;
            string[] res = columnToMove.Split('|');
            sortOrder = Order;//SortOrder.Ascending;
            if (sortOrder == SortOrder.None)
                sortOrder = SortOrder.Ascending;
            sortMode = (DataGridViewColumnSortMode)Enum.Parse(typeof(DataGridViewColumnSortMode), column.SortMode.ToString());
            OutlookGridGroupBoxColumn colToAdd = new OutlookGridGroupBoxColumn(columnName, columnText, sortOrder, groupingType);
            //if (res[4] == typeof(OutlookGridDateTimeGroup).Name)
            colToAdd.GroupInterval = res[0];
            colToAdd.SortBySummaryCount = sortBySummary;
            if (!String.IsNullOrEmpty(columnToMove) && !columnsList.Contains(colToAdd) && sortMode != DataGridViewColumnSortMode.NotSortable)
            {
                /*
                //Determine the position of the new Group amongst the others 
                int i = 0; //first group order is 0
                //We are sure that we are going to browse the columns from left to right
                foreach (OutlookGridGroupBoxColumn existingColumn in this.columnsList)
                {
                    if (e.X > (existingColumn.Rect.X + existingColumn.Rect.Width / 2))
                    {
                        i++;
                    }
                }
                */
                columnsList.Insert(0, colToAdd);

                //try
                //{
                //Warns the grid of a new grouping
                OnColumnGroupAdded(new OutlookGridColumnEventArgs(new OutlookGridColumn(columnName, null, null, sortOrder, 0, -1)));
                this.Invalidate();
                //}
                //catch (Exception exc)
                //{
                //    MessageBox.Show("Failed to group.\n\n Error:" + exc.Message,
                //                      "Grid GroupBox",
                //                      MessageBoxButtons.OK,
                //                      MessageBoxIcon.Error);
                //}
            }
        }
```

This method is not included neither on the original library nor the new one.  I don't really know from where I have it, probably from github, but it's not mine.  I think it's for creating groups without dragging columns, just by code.  I would use it like this:

`kryptonOutlookGridGroupBox1.CreateGroupBox(kryptonOutlookGrid1.Columns[2], "OutlookGridDefaultGroup", SortOrder.None, true);`

It would crate groups from the values in kryptonOutlookGrid1.Columns[2] and group all the rows of the outlook grid.  Is it possible to add it?  Is there another way to accomplish this?

Thanks!

EDIT: Sorry for the formatting, I don't know how to show the code well

**Comment by Wagnerp** [comment]
Hi @NintendoPlayer thanks for the suggestion. I'll add it to a future update.

**Comment by NintendoPlayer** [comment]
Thanks @Wagnerp!  Just a clarification.  I was thinking about where I got this function.  I can't assure I added it myself, but it is possible, because it's a modified KryptonOutlookGridGroupBox_DragDrop event.  It's the same method, with some minor modifications.  Just let you know where it came from and if I can be "cleaner".  If you need testing let me know, I can test the changes just like the other outlook grid issue.

Thanks!

**Comment by Wagnerp** [comment]
Hi @NintendoPlayer is it possible to attach a copy of the modified library code, as I think that the function attached relies on further modifications?

**Comment by NintendoPlayer** [comment]
Hi @Wagnerp!  Well, of course.  I have attached the KryptonOutlookGridGroupBox control.  I don't think there is modified code in other file, but if you want I can add the whole project.

[KryptonOutlookGrid.zip](https://github.com/Krypton-Suite/Extended-Toolkit/files/7968941/KryptonOutlookGrid.zip)

**Comment by Wagnerp** [comment]
> Hi @Wagnerp! Well, of course. I have attached the KryptonOutlookGridGroupBox control. I don't think there is modified code in other file, but if you want I can add the whole project.
> 
> [KryptonOutlookGrid.zip](https://github.com/Krypton-Suite/Extended-Toolkit/files/7968941/KryptonOutlookGrid.zip)

Hi @NintendoPlayer thanks for the upload, is it possible to add the whole project, as there seems to be modifications in other files? Thanks in advance!

**Comment by NintendoPlayer** [comment]
Hi @Wagnerp!  There you have it!

[KryptonOutlookGrid.zip](https://github.com/Krypton-Suite/Extended-Toolkit/files/7969756/KryptonOutlookGrid.zip)

**Comment by NintendoPlayer** [comment]
Hi @Wagnerp!  Sorry to bother but, are there any news about this feature?  I was using it with the old library and now there is some issues with my apps because programmatically grouping is not working because of the lack of this method.

Thanks!

**Comment by Wagnerp** [comment]
> Hi @Wagnerp! Sorry to bother but, are there any news about this feature? I was using it with the old library and now there is some issues with my apps because programmatically grouping is not working because of the lack of this method.
> 
> Thanks!

Hi @NintendoPlayer At the moment I'm working on this https://github.com/Krypton-Suite/Standard-Toolkit/issues/609. However, hopefully I can work on #290 soon.

**Comment by Wagnerp** [comment]
Hi @NintendoPlayer 

Good news! I've now implemented it, so it'll be in the next nightly build .41, which will be uploaded tomorrow.

**Comment by NintendoPlayer** [comment]
Hi @Wagnerp!  Great news, I will try the feature then!

**Comment by Wagnerp** [comment]
Implemented - 09/02/2022
