### ISSUE TITLE
[Bug]: Starting out with Krypton toolkit Extended

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Extended-Toolkit#297]
Visual Studio 2019 (16.11.9)
VB.Net
Krypton Toolkit 6.2201.4
Krypton Toolkit Extended 6.2113.340

When placing controls I get this

![image](https://user-images.githubusercontent.com/84494183/151658350-5fe157f1-7753-4ea2-8fda-e7d70bf19010.png)

Or this

![image](https://user-images.githubusercontent.com/84494183/151658395-2b744f63-c559-4eae-bd69-8f506aff28c5.png)

It isn't control specific, in general I struggle to use ANY Extended-Toolkit control

There are so many different Extended-tookit packages in Nuget, I can't tell if I've downloaded everything I need, at the right level
Which Toolkit-Extended package should I be using to get additional ComboBox Controls?

**Comment by Wagnerp** [comment]
> There are so many different Extended-tookit packages in Nuget, I can't tell if I've downloaded everything I need, at the right level Which Toolkit-Extended package should I be using to get additional ComboBox Controls?

A upcoming update will improve upon the existing package descriptions

**Comment by Wagnerp** [comment]
> Krypton Toolkit 6.2201.4
Krypton Toolkit Extended 6.2113.340

@MattH-Work 

Build **6.2112.340** is using the November 2021 version of the toolkit, thus it can't use 6.2201.4. Aiming to release a new version next week to use the February update
