### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Extended-Toolkit#299]
Krypton Toolkit 60.22.2.32 already installed

Trying to install Krypton.Toolkit.Extended.?????

Get the following errors (????? replaces relevant item)

Unable to find a version of 'Krypton.Toolkit.Canary' that is compatible with 'Krypton.Toolkit.Suite.Extended????? 60.2202.32 constraint: Krypton.Toolkit.Canary (>= 6.2201.1-beta)'.

Isn't Canary 'beta', is it actually required for ...Extended.??? use

**Comment by Wagnerp** [comment]
Not a bug - please uninstall the canary version of the standard toolkit if using the stable version of the extended toolkit.

**Comment by Wagnerp** [comment]
To be deployed 02/02/2022

**Comment by MattH-Work** [comment]
Cheers
