### ISSUE TITLE
Missing controls

### ISSUE THREAD

**Issue by herledant** [Krypton-Suite/Extended-Toolkit#3]
As you told me, please find below some controls that i don't find in the new package.
Below is the old references:

ExtendedControls.ExtendedToolkit.Controls.KryptonBorderedLabel() - Completed (see v6)
ExtendedControls.ExtendedToolkit.Controls.KryptonToastNotificationPopup() - Completed (Been renamed)
ExtendedControls.ExtendedToolkit.Controls.KryptonControls.KryptonMarqueeLabel() - Completed (see v6)
Krypton.Toolkit.Extended.Common.ExtendedControls.ExtendedToolkit.Controls.Navigator.Controls.KryptonTabPage - Completed (see v6)
ExtendedControls.ExtendedToolkit.Controls.Navigator.Controls.Alternative.KryptonTabControl - Completed (see v6)
ExtendedControls.ExtendedToolkit.Controls.Navigator.Controls.KryptonTabPage - Completed (see v6)
ExtendedControls.ExtendedToolkit.Controls.KryptonControls.KryptonMonthCalendar()
ExtendedControls.ExtendedToolkit.Controls.KryptonToastNotificationPopup - See point 2
ExtendedControls.ExtendedToolkit.Controls.KryptonControls.KryptonComboBox - Completed (see v6)

Regards

**Comment by Smurf-IV** [comment]
What do the `[x]` mean ?

Found and have a new name - location - example

Or part of that "Dead project" ?

**Comment by Wagnerp** [comment]
> What do the `[x]` mean ?
> 
> Found and have a new name - location - example
> 
> Or part of that "Dead project" ?

Those controls were reintroduced into the corresponding modules. Seems that the markdown check did not render.

**Comment by Smurf-IV** [comment]
> 
> Those controls were reintroduced into the corresponding modules. Seems that the markdown check did not render.

Still not sure that answers the questions..
Also some are missing the `[x]`

**Comment by Wagnerp** [comment]
> > Those controls were reintroduced into the corresponding modules. Seems that the markdown check did not render.
> 
> Still not sure that answers the questions..
> Also some are missing the `[x]`

The `[x]` was supposed to indicate that the specific control was implemented.

**Comment by Smurf-IV** [comment]
Can you put the above comment into the Opening Box,
And add another column stating their progress inclusion in the Revamp please ?

**Comment by Wagnerp** [comment]
Available in v6.
