### ISSUE TITLE
[Bug]: KryptonMessageBoxExtended

### ISSUE THREAD

**Issue by dhero-optum** [Krypton-Suite/Extended-Toolkit#307]
I couldn't find the method to show the message box and noticed that the class is blank. Not sure if this is intended or will be available in a future release? 

![image](https://user-images.githubusercontent.com/62311834/157987637-c85a79da-f97e-46e2-8cd7-0f4dfcc0a4a5.png)

Am i using this correctly??

thanks!

**Comment by Wagnerp** [comment]
> I couldn't find the method to show the message box and noticed that the class is blank. Not sure if this is intended or will be available in a future release?
> 
> ![image](https://user-images.githubusercontent.com/62311834/157987637-c85a79da-f97e-46e2-8cd7-0f4dfcc0a4a5.png)
> 
> Am i using this correctly??
> 
> thanks!

Hi @dheroOptum 

Are you using the current nightly build?

**Comment by dhero-optum** [comment]
Hi Peter!
Thank you for the reply! i switched over to nightly and i can see it now. Thanks! :)
