### ISSUE TITLE
[Question]: Why does the Outlook Grid module have so many dependencies?

### ISSUE THREAD

**Issue by Ahmed-Abdelhameed** [Krypton-Suite/Extended-Toolkit#31]
Hello and thanks for the great work,

So, I've been using the original [Krypton Suite](https://github.com/ComponentFactory/Krypton) (v4.5) for a while (or v4.4.1 from [this fork](https://github.com/Cocotteseb/Krypton-OutlookGrid) for when I need to use the `OutlookGrid`). I've recently switched to the newer versions of the Standard Toolkit for High DPI support and it's been working fine with little tweaks.

Now, I would like to use the `OutlookGrid` again. So, I tried getting it from [this NuGet package](https://www.nuget.org/packages/Krypton.Toolkit.Suite.Extended.Outlook.Grid) but its dependencies include `Krypton.Toolkit.Canary` (why Canary?) and `Krypton.Toolkit.Suite.Extended.Dialogs` (which has many other dependencies). So, I end up with a lot of packages that I don't need (I only use `Krypton.Toolkit` and `Krypton.Navigator`):

```
<packages>
  <package id="CommandLineParser" version="2.8.0" targetFramework="net472" />
  <package id="Cyotek.Windows.Forms.ColorPicker" version="1.7.2" targetFramework="net472" />
  <package id="EasyScintilla" version="1.0.5" targetFramework="net472" />
  <package id="jacobslusser.ScintillaNET" version="3.6.3" targetFramework="net472" />
  <package id="Krypton.Docking.Canary" version="6.0.2008" targetFramework="net472" />
  <package id="Krypton.Navigator.Canary" version="6.0.2008" targetFramework="net472" />
  <package id="Krypton.Ribbon.Canary" version="6.0.2008" targetFramework="net472" />
  <package id="Krypton.Toolkit.Canary" version="6.0.2008" targetFramework="net472" />
  <package id="Krypton.Toolkit.Suite.Extended.Base" version="5.550.2010" targetFramework="net472" />
  <package id="Krypton.Toolkit.Suite.Extended.Common" version="5.550.2010" targetFramework="net472" />
  <package id="Krypton.Toolkit.Suite.Extended.Core" version="5.550.2010" targetFramework="net472" />
  <package id="Krypton.Toolkit.Suite.Extended.Dialogs" version="5.550.2010" targetFramework="net472" />
  <package id="Krypton.Toolkit.Suite.Extended.Drawing.Suite" version="5.550.2010" targetFramework="net472" />
  <package id="Krypton.Toolkit.Suite.Extended.Global.Utilities" version="5.550.2010" targetFramework="net472" />
  <package id="Krypton.Toolkit.Suite.Extended.Language.Model" version="5.550.2010" targetFramework="net472" />
  <package id="Krypton.Toolkit.Suite.Extended.Outlook.Grid" version="5.550.2010" targetFramework="net472" />
  <package id="Krypton.Toolkit.Suite.Extended.Palette.Controls" version="5.550.2010" targetFramework="net472" />
  <package id="Krypton.Toolkit.Suite.Extended.Settings" version="5.550.2010" targetFramework="net472" />
  <package id="Krypton.Toolkit.Suite.Extended.Standard.Controls" version="5.550.2010" targetFramework="net472" />
  <package id="Krypton.Toolkit.Suite.Extended.Utilities" version="5.550.2010" targetFramework="net472" />
  <package id="Krypton.Workspace.Canary" version="6.0.2008" targetFramework="net472" />
  <package id="Microsoft.VisualBasic" version="10.3.0" targetFramework="net472" />
  <package id="System.Management" version="4.7.0" targetFramework="net472" />
  <package id="System.Runtime" version="4.3.1" targetFramework="net472" />
  <package id="System.Text.RegularExpressions" version="4.3.1" targetFramework="net472" />
  <package id="WindowsAPICodePack" version="1.1.1" targetFramework="net472" />
</packages>
```
So, is there a version of the `OutlookGrid` that doesn't require all those dependencies?

Also, to be honest, I'm not so confident in the Extended-Toolkit as I found many glitches when I tried to test some of its controls. So, I'd like to stick with the Standard-Toolkit and add the `OutlookGrid` module to it, if possible.

Thank you!

**Comment by Wagnerp** [comment]
Hi @Ahmed-Abdelhameed 

Thanks for the question, the reason why the extended-toolkit uses the `Canary` version of the Standard-Toolkit (for the moment) is that it was rewritten for the upcoming features in Standard-Toolkit build 2011. Please refer to build 2004 for brief explanation. As for the `OutlookGrid`, it's going to be completely rewritten for .NET Core, hence all the dependencies, as .NET Core works very differently from the older .NET Framework.

**Comment by Ahmed-Abdelhameed** [comment]
Hi @Wagnerp 

Thanks a lot for the quick reply! There are two points that I'm not sure I understand:

1. Are the dependencies that are part of the Krypton Suite (eg., `.Extended.Dialogs`, `.Extended.Utilities`, etc.) also required to build for .NET Core (when they're not needed but the `OutlookGrid`, AFAICT)?
2. If my project is targeting .NET Framework (e.g., 4.7.2), why does the `OutlookGrid` module still have all those dependencies? Shouldn't the dependencies change based on what .NET version the client project is targetting?

What I'm basically trying to achieve is to use the Standard Toolkit + the maintained version of `OutlookGrid` without having all the (seemingly) unnecessary dependencies. Is there a path for this to work? Or are my only options to either live with those dependencies or use an older version of `OutlookGrid`?

Thanks again for all the great work :)

**Comment by Wagnerp** [comment]
Hi @Ahmed-Abdelhameed 

Thanks for the reply. I'm going to rewrite the `OutlookGrid` module, this time keeping the dependencies to a minimal. There will be some such as `Microsoft.VisualBasic`, `System.Management`, `System.Runtime` & `System.Text.RegularExpressions` along with `Krypton.Toolkit`, as these had to be rewritten for .NET Core/.NET. Target release is February 2021.
