### ISSUE TITLE
[Feature Request]: Is it possible to add es-ES language?

### ISSUE THREAD

**Issue by NintendoPlayer** [Krypton-Suite/Extended-Toolkit#315]
Right now there is EN and FR language files for the OutlookGrid.  Is it possible to add ES-es?  I could translate the Strings.xx-XX.resx file

Thanks!

**Comment by NintendoPlayer** [comment]
HI  @Wagnerp!  Sorry, but I've never created a new PR, I think I can do it but I don't wanna mess anything :D.  I already have the new file, it's attached as zip, because .resx was not accepted

[Strings.es-ES.zip](https://github.com/Krypton-Suite/Extended-Toolkit/files/8670308/Strings.es-ES.zip)

**Comment by Wagnerp** [comment]
Implemented - 12/05/2022
