### ISSUE TITLE
NuGet Installation Error in v65.22.6.152 Version - NU1103 Rollback

### ISSUE THREAD

**Issue by mikel3361** [Krypton-Suite/Extended-Toolkit#324]
Using Visualstudio 2017 VB with FrameWork 4.72 get following Error wenn i try to install current Extended Version on some packages. Not installed Krypton has Nightly References inside:

![image](https://user-images.githubusercontent.com/42733572/173572217-c9ea33a2-59f7-4744-a570-6cdcca7cda03.png)
![image](https://user-images.githubusercontent.com/42733572/173572312-1308f5c6-9e94-45b1-ac32-dcc5fa736946.png)
![image](https://user-images.githubusercontent.com/42733572/173572400-7c5aeb87-2499-496d-980e-fb48ce9213c3.png)
![image](https://user-images.githubusercontent.com/42733572/173572477-97eb6669-e747-4a4e-97cc-e10e2a8a25c7.png)
![image](https://user-images.githubusercontent.com/42733572/173572583-0105752d-cd03-44f3-8f16-86ace4300c25.png)
![image](https://user-images.githubusercontent.com/42733572/173572700-58e6c74a-95d5-4369-ae02-dfa0b9229cc5.png)
![image](https://user-images.githubusercontent.com/42733572/173572789-ceb4f217-af0b-4fc6-b180-c26ce4f461be.png)
...

_Originally posted by @mikel3361 in https://github.com/Krypton-Suite/Standard-Toolkit/issues/753#issuecomment-1155093182_

**Comment by Wagnerp** [comment]
@Smurf-IV Is there any way to 'link' the standard toolkit into the extended toolkit like the demos, as using NuGet packages is causing chaos?

**Comment by Smurf-IV** [comment]
Not sure I understand the question, as this item seems to go round a bit.
Can you lay out the steps to the problem as you see it please ?

**Comment by Wagnerp** [comment]
> Not sure I understand the question, as this item seems to go round a bit. Can you lay out the steps to the problem as you see it please ?

Yes of course, the problem at the moment is that the extended toolkit relies on the Krypton NuGet packages to build it, this is ok if you have one configuration i.e. `Nightly` but messes up when there is multiple configurations. To simplify things, would it be possible to use the standard toolkit directly?

i.e

![image](https://user-images.githubusercontent.com/949607/174013301-e96ed0f3-269c-417b-ab74-b44996a16968.png)

**Comment by Smurf-IV** [comment]
No that will not work in production either..
Will need to use something akin to dynamic loading for versions x and above. 
Something that MS are "still experimenting" with for the runtime.
This is where the c# Dependency injection tries to solve, but it is really slow for multiple classes.
I'm sure there is another way.. Just cannot think on it at the moment, As I'm in MFC / stl / std / C++ hell :-!

**Comment by mikel3361** [comment]
All references in the standard toolkit are well. Must be in the extended version on nuget.
![image](https://user-images.githubusercontent.com/42733572/175517120-5a75086a-f82f-40c7-b3cb-520213e9f6c4.png)

**Comment by Wagnerp** [comment]
Is there a way to produce some sort of diagram to see which packages are getting pulled in?

**Comment by mikel3361** [comment]
Takes a little bit ... i do it and post the error logs...

**Comment by mikel3361** [comment]
![image](https://user-images.githubusercontent.com/42733572/175519513-2b9d1a1f-1a0c-4529-a28c-b5118f5c742b.png)
![image](https://user-images.githubusercontent.com/42733572/175519672-265a65fb-4f66-49b3-92dd-fd77e1851d20.png)
![image](https://user-images.githubusercontent.com/42733572/175519829-f18b2821-23fb-43da-a19e-942c8c5b608e.png)
![image](https://user-images.githubusercontent.com/42733572/175519936-08b88d55-3e1b-4f14-b48d-f30a6e07491b.png)
![image](https://user-images.githubusercontent.com/42733572/175520127-42fc4c6e-1617-4283-a1d0-0a864c4a509c.png)
![image](https://user-images.githubusercontent.com/42733572/175520248-25b64204-f919-41ab-8ba7-8160818d9b6d.png)
![image](https://user-images.githubusercontent.com/42733572/175520413-6b0b3726-6517-48ef-b51e-4d4088352954.png)
![image](https://user-images.githubusercontent.com/42733572/175520589-4b32ec0f-7cf2-43b3-a62d-6f2d9907fa0a.png)
![image](https://user-images.githubusercontent.com/42733572/175520687-6e81acc6-c963-43a1-881e-0342c9fbb18b.png)
![image](https://user-images.githubusercontent.com/42733572/175520797-a1126872-c438-4f2b-a091-834115ec05e6.png)
![image](https://user-images.githubusercontent.com/42733572/175521154-2d956f5f-003a-4b0c-8f9d-f7d331a16b04.png)
![image](https://user-images.githubusercontent.com/42733572/175521269-ef257af4-4718-4d32-891a-825ebe81b8f4.png)
![image](https://user-images.githubusercontent.com/42733572/175521387-59f2defc-ab62-4314-9135-f547d30f1fa4.png)
![image](https://user-images.githubusercontent.com/42733572/175521497-66037a2c-9587-404f-82e1-eba1c9a91f3b.png)
![image](https://user-images.githubusercontent.com/42733572/175521692-8d2a1b38-593a-4e59-ade4-a80b0d436890.png)
![image](https://user-images.githubusercontent.com/42733572/175521769-2d9df08d-a02b-4264-a298-44d073aae1be.png)
![image](https://user-images.githubusercontent.com/42733572/175521912-7b429551-37de-4d2f-977c-b6de64732578.png)
![image](https://user-images.githubusercontent.com/42733572/175522007-acff0868-5bb4-4755-992b-b55d1d7ddfb0.png)
![image](https://user-images.githubusercontent.com/42733572/175522172-8476d3ea-c884-4213-9c0a-5da2d946ad9d.png)
![image](https://user-images.githubusercontent.com/42733572/175522283-ed3f5c81-647f-4ddb-895c-b9b1743a57d8.png)

**Comment by mikel3361** [comment]
All other packages from this version are clean to install - hope i don't miss something...

**Comment by Wagnerp** [comment]
I wonder if there is something wrong with this?

```xml
<Choose>
		<When Condition="'$(SolutionName.Endswith(`NuGet`))'">
			<Choose>
				<When Condition="'$(Configuration)' == 'Nightly'">
					<PropertyGroup>
						<LangVersion>preview</LangVersion>
					</PropertyGroup>

					<ItemGroup>
						<PackageReference Include="Krypton.Toolkit.Nightly" Version="70.22.6.175-alpha" />
					</ItemGroup>
				</When>
				<Otherwise>
					<Choose>
						<When Condition="'$(Configuration)' == 'Canary'">
							<PropertyGroup>
								<LangVersion>preview</LangVersion>
							</PropertyGroup>

							<ItemGroup>
								<PackageReference Include="Krypton.Toolkit.Canary" Version="65.22.5.123-beta" />
							</ItemGroup>
						</When>
						<Otherwise>
							<Choose>
								<When Condition="'$(Configuration)' == 'Signed'">
									<PropertyGroup>
										<LangVersion>preview</LangVersion>
									</PropertyGroup>

									<ItemGroup>
										<PackageReference Include="Krypton.Toolkit.Signed" Version="65.22.6.152" />
									</ItemGroup>
								</When>
								<Otherwise>
									<PropertyGroup>
										<LangVersion>preview</LangVersion>
									</PropertyGroup>

									<ItemGroup>
										<PackageReference Include="Krypton.Toolkit" Version="65.22.6.152" />
									</ItemGroup>
								</Otherwise>
							</Choose>
						</Otherwise>
					</Choose>
				</Otherwise>
			</Choose>
		</When>
		<Otherwise>
			<ItemGroup>
				<ProjectReference Include="..\..\..\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Krypton.Toolkit 2022.csproj" />
			</ItemGroup>
		</Otherwise>
	</Choose>
```

**Comment by mikel3361** [comment]
I Think nan be simplified - maybe too many choose/otherwise implemented.
Choose
   When ...
   When ...
   When ...
   Otherwise (all When's False)
 //Choose
 Do not use it by myself, only what i think after read microsoft docs...

**Comment by Wagnerp** [comment]
> I Think nan be simplified - maybe too many choose/otherwise implemented. Choose When ... When ... When ... Otherwise (all When's False) //Choose Do not use it by myself, only what i think after read microsoft docs...

I'll have a look into it tomorrow

**Comment by xxl-cc** [comment]
I have same problem， some stable version dependent nightly version

**Comment by Wagnerp** [comment]
@mikel3361 Resolved, but the changes won't take effect until v70

cc. @Smurf-IV

**Comment by mikel3361** [comment]
Can't await V7 comes out - would changes soon be available in beta version? ;-)

**Comment by Wagnerp** [comment]
> Can't await V7 comes out - would changes soon be available in beta version? ;-)

Yes, in the next beta
