### ISSUE TITLE
[Feature Request]: `KryptonProgressBar` add text attribute

### ISSUE THREAD

**Issue by xxl-cc** [Krypton-Suite/Extended-Toolkit#330]
**Is your feature request related to a problem? Please describe.**
Can kryptonprogressbar add text attribute？

**Describe the solution you'd like**
I want to display text messages inside the progress bar

**Comment by Wagnerp** [comment]
I do remember creating such a control, not sure if it is still in here though?

**Comment by Wagnerp** [comment]
Hi @xxl-cc is this what you mean?

![KPBE](https://user-images.githubusercontent.com/949607/176389110-3c21fe8c-7130-4d3a-87c8-8c8e25a768ff.gif)

**Comment by Smurf-IV** [comment]
Yes via this:
```c#
 [Category("Value"), DefaultValue(""), Description("The text that is displayed on the progress bar.")]
        public string DisplayText
        {
            get => _displayText;
            set => _displayText = value;
        }
```

**Comment by Wagnerp** [comment]
Update 2:

![KPBE](https://user-images.githubusercontent.com/949607/176855138-04f211ad-1cff-4e82-863a-116b8442e6c2.gif)

**Comment by Wagnerp** [comment]
Closing, due to no response. Feature has been implemented in v70.
