### ISSUE TITLE
[Feature Request]: One Krypton Extended Toolkit NuGet package to rule them all

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Extended-Toolkit#331]
In a similar way to the Standard toolkit, could we have a build of the Extended toolkit that is just one self contained file, with all the different controls meged into one package
While I appreciate the size of the package would increase, the management of the package(s) from our end would be much simpler
The NuGet experiance would be greatly improved
![image](https://user-images.githubusercontent.com/84494183/176148608-81af7f69-52be-4687-b249-48c3f09d92c5.png)

**Comment by mikel3361** [comment]
For easier adding of all components a NuGet package that adds all other packages to a project would be helpful.

**Comment by Wagnerp** [comment]
Could be useful https://docs.microsoft.com/en-us/nuget/reference/nuspec#example-nuspec-files

**Comment by mikel3361** [comment]
I personally use it via the package.reference file and after creating it once, I only need to copy and paste it into a new project. Then download NuGet files and everything is ok. Only complicated if you switch between version (to try out beta) - For me a way that is ok, thought only one could additionally add a Nuget...complete package roll out....

**Comment by Wagnerp** [comment]
@mikel3361 

Good news!

Will be creating an 'Ultimate' package for the November release!

**Comment by Wagnerp** [comment]
Completed - 08/11/2022
