### ISSUE TITLE
[Feature Request]: Krypton.Toolkit.Suite.Extended.Outlook.Grid - language support german

### ISSUE THREAD

**Issue by mikel3361** [Krypton-Suite/Extended-Toolkit#334]
Could you also include german as a language for the Outlook.grid. I have translated the resource as good as possible and attached.

[Krypton.Toolkit.Suite.Extended.Outlook.Grid.Languague.Strings.de-DE.resx.zip](https://github.com/Krypton-Suite/Extended-Toolkit/files/9017091/Krypton.Toolkit.Suite.Extended.Outlook.Grid.Languague.Strings.de-DE.resx.zip)

**Comment by mikel3361** [comment]
Sorry, out of office until July 25. Check it later

**Comment by Wagnerp** [comment]
Ok, no problem

**Comment by mikel3361** [comment]
Form/Control does not respond to language settings at all. This may be due to VB.net or Windows installation. No matter what I set it always shows Default. But I would release it like this - it's surely me. Also other controls do not react on changing the language. I am still looking for the cause.

**Comment by Wagnerp** [comment]
It might be a issue in `Krypton.Toolkit.Suite.Extended.Outlook.Grid\Classes\Utilities\Language\LanguageManager.cs`

**Comment by mikel3361** [comment]
Wouldn't it be better to keep the texts as a property in the grid like in KryptonManager and to react on language settings like standard controls? Then you could take care of your translation yourself according to your preference without having unnecessary translations in your project.

**Comment by Wagnerp** [comment]
> Wouldn't it be better to keep the texts as a property in the grid like in KryptonManager and to react on language settings like standard controls? Then you could take care of your translation yourself according to your preference without having unnecessary translations in your project.

That might be a good new feature request

**Comment by Wagnerp** [comment]
Hi @mikel3361 

Can you test using todays nightly please 215, as I've re-worked it to use a settings database

**Comment by mikel3361** [comment]
Not the best sample - don't know where to see localized text, but Colums react on language changes. The Popup-menu seems not show changes. german localization is present. I realy do not know what is happend...
Maybe a better Testapp, but currently no Time for it. GroupBox lost Localized strings on reopen - only default. (213)
![image](https://user-images.githubusercontent.com/42733572/182553604-a3891fde-6936-4fbd-b788-bf1ca8c42240.png)

**Comment by mikel3361** [comment]
As i mentioned before - properties should be better. GroupBox lost localisation....

**Comment by Wagnerp** [comment]
Hi @mikel3361 

I think I put these under a property called 'LanguageSettings' if I recall

**Comment by Wagnerp** [comment]
Refined to use properties, instead of `resx` files

**Comment by Wagnerp** [comment]
Closing, due to the use of properties
