### ISSUE TITLE
[Feature Request]: KryptonDataGridViewCheckBoxColumn with Label inside cell

### ISSUE THREAD

**Issue by mikel3361** [Krypton-Suite/Extended-Toolkit#335]
It's possible to give the CheckBoxColumn/Cell a optional label to display text - no edit required but font attibutes where nice.
Currently i use two columns for that but all in one column wold be easier...

**Comment by Smurf-IV** [comment]
Can you show a "Mock-up" or an equivalent from another package.
As the layout options for such "Labelling" can be numerous

**Comment by mikel3361** [comment]
SyncFusion DataGridView have this Option but i switched to Krypton. Caption (Label) beside CheckBox can be formated with Font, Forecolor Attributes.
![image](https://user-images.githubusercontent.com/42733572/176841635-cd6df7f5-eb9d-4991-80fe-143d035162db.png)

**Comment by Smurf-IV** [comment]
The column types in the data grid (If using the Krypton equivalents) still have the Krypton styling. 

If you place an non grid version one on the form and style it, then look at the designer to see the styles, they then can be applied to the Krypton column type (Or so I thought ?)

**Comment by mikel3361** [comment]
I have not noticed so far - I'll try it out

**Comment by mikel3361** [comment]
I could not manage with the assignment. Now I have CheckBoxColumn via Inherit Customized with Label and LabelColor and can work with it.

![image](https://user-images.githubusercontent.com/42733572/177942070-6420c56d-1294-4ea7-b67c-c11eb7e9fb15.png)
