### ISSUE TITLE
[Bug]: build failure The "ResolvePackageAssets" task was not given a value for the required parameter "TargetFramework".	

### ISSUE THREAD

**Issue by lynnewu** [Krypton-Suite/Extended-Toolkit#337]
**Describe the bug**
When attempting to build the Extended-Toolkit using "Krypton Toolkit Suite Extended 2022  - VS2022 - Dev.sln" the following error message is shown for every sub-project:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4044	The "ResolvePackageAssets" task was not given a value for the required parameter "TargetFramework".	Krypton.Toolkit.Suite.Extended.TaskDialogs 2022	C:\Program Files\dotnet\sdk\6.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	267	

```

**To Reproduce**
Open "Krypton Toolkit Suite Extended 2022  - VS2022 - Dev.sln" in Visual Studio 2022.  
Build solution
Check "Error List" window for messages.  

**Expected behavior**
Should build

**Screenshots**
![image](https://user-images.githubusercontent.com/877133/176709436-0db098e8-f7eb-44ba-b149-7592a95f1faa.png)

**Desktop (please complete the following information):**
Windows 10
Visual Studio (64-bit) 2022 Version 17.2.5

Krypton Suite Extended toolkit versions Stable and Canary

**Comment by Wagnerp** [comment]
Linked to #324, which has been resolved. Closing due to changes made in PR #332.
