### ISSUE TITLE
[Feature Request]: Expose the OutlookGrid.Classes.OutlookGridRowComparer2 class

### ISSUE THREAD

**Issue by Ahmed-Abdelhameed** [Krypton-Suite/Extended-Toolkit#36]
**Is your feature request related to a problem? Please describe.**
Because of the custom sorting logic of the OutlookGrid, the `SortCompare` event can no longer be used to override the comparing logic. AFAICT looking at the source, the only alternative would be to change the logic or the `IComparer` that is used for sorting the `internalRows` list. However, it's currently hardcoded to `OutlookGridRowComparer2`, which is `internal` so it can't be inherited.

**Describe the solution you'd like**
There are two possible (similar) solutions I can think of:
1. Simply expose the `OutlookGridRowComparer2` class by making it `public` (quick & easy change)
2. Add a `RowComparer` property of type `IComparer<OutlookGridRow>` to the grid class so one can provide any custom comparer (arguably better but requires more changes). I can work on a PR if you think this is better but I think option 1 above is good enough.

**Describe alternatives you've considered**
The only other option I could think of (without modifying the source) is to override the `Fill()` method altogether but that's a huge overkill to do just for changing the comparer, not to mention that any changes to the original `Fill()` method would need to be manually added after each update.

**Additional context**
I'm aware that there's the option to change `OutlookGridColumn.GroupingType.ItemsComparer`. However, that's only useful when one merely needs to compare two values without any additional context. You can't access the values of other cells or get the underlying object bound to the row, for example.

If you think there's a better solution, please let me know. Thank you!

**Comment by Wagnerp** [comment]
Hi @Ahmed-Abdelhameed 

I'm going to redo the module, as there are so many bugs in it, so I'll take your request into account.

**Comment by Wagnerp** [comment]
@Ahmed-Abdelhameed 

Could do both options to suit the developer needs.

**Comment by Cocotteseb** [comment]
Hi @Ahmed-Abdelhameed,
You can already specify your own Comparer (: IComparer) on the GridGroup object with the property ItemsComparer which can be different for each column if you want to overwrite the default logic.
That should do what you need ;)

**Comment by Ahmed-Abdelhameed** [comment]
Hi @Cocotteseb,
Please refer to the "Additional context" section of the OP. As I explained above, that doesn't provide the same level of flexibility that one has with the original `SortCompare` event. Anyway, for my use case, I modified an older version of the module and made it raise a `new` SortCompare event with a custom `EventArgs`. I could share that in a gist or something if @Wagnerp thinks it would be useful.

**Comment by Wagnerp** [comment]
Hi @Ahmed-Abdelhameed 

If you can share a gist, that would be great. I'm currently waiting for a new PC, as my old one was close to dying (I think MS Flight Simulator 2020 may have killed it ;)) so development may be slow for a few weeks.

**Comment by Ahmed-Abdelhameed** [comment]
Hi @Wagnerp 

Okay, instead of creating a gist of the changed files, I created a repository for the Outlook Grid project which was taken from the [Krypton-Toolkit-Suite-Extended-NET-5.472](https://github.com/Krypton-Suite-Legacy-Archive/Krypton-Toolkit-Suite-Extended-NET-5.472) repository. You can review the history ([relevant commit](https://github.com/Ahmed-Abdelhameed/Krypton-Outlook-Grid-5.472/commit/e703d69658fc719f52a6c2d99587ff3104795a25)) for the changed files.

I must admit this isn't perfectly robust. I just wanted something that works and this does the job. Please let me know if you have any questions about the changes.
