### ISSUE TITLE
[Bug]: `ExtendedMessageBox` does not support `CancelTryContinue` when built for "ANY" of the supported TFM's

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Extended-Toolkit#378]
The following code is incorrect and will not build because the enum is not named liked that:
``` c#
#if NET60_OR_GREATER
                case ExtendedMessageBoxButtons.CANCELTRYCONTINUE:
```
Also the idea of using that is to make it work for any TFM.

**Comment by Wagnerp** [comment]
Pushing a `nightly` build tomorrow (16/12/2022) that includes modifications carried over from https://github.com/Krypton-Suite/Standard-Toolkit/pull/869

**Comment by Wagnerp** [comment]
Resolved 20/12/2022
