### ISSUE TITLE
[Feature Request]: Extended Toolkit Solution needs to have the `Examples` in it

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Extended-Toolkit#379]
So that they can be checked in with the code to prove stuff still Compiles / Works !

![image](https://user-images.githubusercontent.com/2418812/206905295-eaca78e5-1908-416d-ae37-fb0d290ab1d0.png)

**Comment by Wagnerp** [comment]
Ahh, have to rename the 'Testing' folder to 'Examples'

**Comment by Wagnerp** [comment]
Done

![image](https://user-images.githubusercontent.com/949607/206917563-c1456e5e-a427-4ad4-a49a-4fdd03070d16.png)

**Comment by Smurf-IV** [comment]
What happened to the example code that I wrote to test the DataGrid ?
I cannot find it in the repo anymore ....

**Comment by Wagnerp** [comment]
> What happened to the example code that I wrote to test the DataGrid ? I cannot find it in the repo anymore ....

@Smurf-IV Is it in https://github.com/Krypton-Suite/Extended-Toolkit-Demos?

**Comment by Smurf-IV** [comment]
> > What happened to the example code that I wrote to test the DataGrid ? I cannot find it in the repo anymore ....
> 
> @Smurf-IV Is it in https://github.com/Krypton-Suite/Extended-Toolkit-Demos?

Oh wow, That needs a lot of work.
i.e 
- A readme 
- a link to it from the appropriate Landing pages
- A compile
- An update to 2022
-  etc.

**Comment by Wagnerp** [comment]
> What happened to the example code that I wrote to test the DataGrid ? I cannot find it in the repo anymore ....

@Smurf-IV Found them... will be reintroducing them :)
