### ISSUE TITLE
[Feature Request]: Convert the shared projects over to libraries instead of NuGet packages

### ISSUE THREAD

**Issue by Wagnerp** [Krypton-Suite/Extended-Toolkit#386]
Reduce the number of shared projects down to 1 `Common` project

**Comment by Smurf-IV** [comment]
If this is going to happen, then make sure "ANY" third-party nugets are clearly listed with their licensing. AS this could make it into a big No-no for some projects !

**Comment by Smurf-IV** [comment]
Or, Have 2 options !

**Comment by Wagnerp** [comment]
> If this is going to happen, then make sure "ANY" third-party nugets are clearly listed with their licensing. AS this could make it into a big No-no for some projects !

@Smurf-IV What I mean is reduce these:

![image](https://user-images.githubusercontent.com/949607/209116604-7ada8431-b34a-41cc-b424-70baf238005c.png)

At the moment, there are 48 packages, if we could get rid of 6 of them, it'll reduce it to ~42

**Comment by Smurf-IV** [comment]
Or, Convert them to `lib`raries, then they will only be pulled into the shipping Dll's when needed, and only components needed will be in the dll.
