### ISSUE TITLE
[Bug]: Fix fallout from the removal of `PaletteModeManager` type

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Extended-Toolkit#389]
@Wagnerp FYI:
- Remove confusing usage of `PaletteModeManager` and `PaletteMode`
- Fix fallout from type removal
- Now a single set of strings for the theme names

#https://github.com/Krypton-Suite/Standard-Toolkit/issues/827

**Comment by Wagnerp** [comment]
Fixed 04/01/2023
