### ISSUE TITLE
[Bug]: `OutloookGrid` casts error when executing `.Fill()`

### ISSUE THREAD

**Issue by Bonio55** [Krypton-Suite/Extended-Toolkit#414]
Hi there, 

Im not quite sure is the issue I have been experienceing is a bug with the OutlookGrid or more my use of it but whenever i attempt to use the .Fill() command I would recieve 'cast' errors since upgraing to the lastest version on the controls on nuget (previously was using 5.4.7.2 from source).

When previously using the  5.4.7.2 I had also had to make some changed to the code to get it to opperate as expected and have reapplied some changes that I made to this when was previously using 5.4.7.2 to the lastest source code which seems to have brought the control to operating the way i was expecting and without a 'cast' error. Im still not sure if this fixed the issue or again if have been using it incorrectly but I  have included screenshots of my code changes incase these changes are of any use to anyone or if indeed this this is a bug and helps towards a solution. Apollogise if this is incorrectly listed as wasnt sure what to list this under.

Kind Regards 

Shaun

*** Changes to KryptonOutlookGrid.cs ***
![Screenshot_1](https://user-images.githubusercontent.com/39240946/226896653-3c09df23-2f8b-45c0-ab86-ec719d0ebb9c.png)
![Screenshot_2](https://user-images.githubusercontent.com/39240946/226896658-497ec8aa-30c9-4e2c-87b5-df9f56ff7089.png)

*** Changes to FormattingCell.cs ***
![Screenshot_3](https://user-images.githubusercontent.com/39240946/226896668-914bf274-5494-4110-9f9e-75bc92d40daf.png)

**Comment by Wagnerp** [comment]
Hi @Bonio55 

Is this occurring in the newest release?

**Comment by Bonio55** [comment]
buyt again was not sure if was usign the controll incorrecly? only that the changes above fixed my particular issues with using the control

**Comment by Wagnerp** [comment]
So, is the code in the screenshots correct? If so, I'll reintroduce it.

**Comment by Bonio55** [comment]
The codei nthe screenshots is partialy code re added from version 5.4.7.2  and partialy ammended code that I have made with regards to the 5.4.7.2 that had casting issues with also... I have attached the ammended files I have made so you can compare but i can only comment that as far as my implemenation of the control that I am not recieving a casting error any more having made these changes.

[OutlookGrid Changes.zip](https://github.com/Krypton-Suite/Extended-Toolkit/files/11039863/OutlookGrid.Changes.zip)

File Paths
\Krypton.Toolkit.Suite.Extended.Outlook.Grid\Classes\Custom Columns\FormattingCell.cs
\Krypton.Toolkit.Suite.Extended.Outlook.Grid\Classes\General\KryptonOutlookGrid.cs

**Comment by Wagnerp** [comment]
Fixed 03/04/2023
