### ISSUE TITLE
[Bug]: Upgrading v7 to v8 - 'Failed to add reference to 'WebView2Loader'		

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Extended-Toolkit#441]
Via Nuget, when upgrading _Krypton.toolkit.suite.extended.ultimate_ for an existing app to use v8, OR, installing v8 from scratch in new solution I am presented with the following error

Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to add reference to 'WebView2Loader'.
Please make sure that the file is accessible, and that it is a valid assembly or COM component.	

	
![image](https://github.com/Krypton-Suite/Extended-Toolkit/assets/84494183/2dc4b0a7-1ed3-4a82-a829-d8eec1905b92)

**Comment by MattH-Work** [comment]
I should note that my app has no reference or requirement for WebView2, so I assume its required as part of Krypton directly

**Comment by Wagnerp** [comment]
Hi @MattH-Work 

I think that was a left over from the `Software Updater` module. Will remove the affected binaries & issue a new package.

**Comment by MattH-Work** [comment]
Cheers

**Comment by MattH-Work** [comment]
Ultimate build .320 has done the trick
Cheers
