### ISSUE TITLE
[Bug]: v8 - Krypton.Toolkit.Suite.Extended.AdvancedDataGrid

### ISSUE THREAD

**Issue by MattH-Work** [Krypton-Suite/Extended-Toolkit#442]
Looking to try out the new AdvancedDataGrid

Upon install, an error is thrown

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to find a version of 'Krypton.Toolkit.Suite.Extended.Developer.Utilities' that is compatible with 'Krypton.Toolkit.Suite.Extended.AdvancedDataGridView 80.23.11.318 constraint: Krypton.Toolkit.Suite.Extended.Developer.Utilities (>= 80.23.11.318)'.				
![image](https://github.com/Krypton-Suite/Extended-Toolkit/assets/84494183/7921a374-a91f-4115-8a1d-97bb2db2a87b)

There is not currently an appropriate version of the Dev utilities ( I assume ADG is looking for Dev Utils v 80.23.11.318 NOT v 65.22.4.94 )
![image](https://github.com/Krypton-Suite/Extended-Toolkit/assets/84494183/79ef9583-90c2-4c54-b013-9c5bc6d11cd8)

**Comment by Wagnerp** [comment]
Hi @MattH-Work 

Please remove the old 'shared' packages, as these binaries are now bundled into the toolkit itself.

This is a list of them

![image](https://github.com/Krypton-Suite/Extended-Toolkit/assets/949607/63f0ae9a-e3ee-43fc-b899-8ecc5abdcee8)

**Comment by MattH-Work** [comment]
I haven't got any of the listed pckages installed
New blank solution, used Nuget to install "Krypton.Toolkit.Suite.Extended.AdvancedDataGridView", error thrown

**Comment by Wagnerp** [comment]
> I haven't got any of the listed pckages installed New blank solution, used Nuget to install "Krypton.Toolkit.Suite.Extended.AdvancedDataGridView", error thrown

Which packages have you got installed?

**Comment by MattH-Work** [comment]
None.
For testing the AdvancedDataGrid I started a brand new solution ( Visual Studio 2022, VB.net by the way ), installed the Krypton.Toolkit.Suite.Extended.AdvancedDataGridView package from Nuget and received the error

**Comment by Wagnerp** [comment]
> None. For testing the AdvancedDataGrid I started a brand new solution ( Visual Studio 2022, VB.net by the way ), installed the Krypton.Toolkit.Suite.Extended.AdvancedDataGridView package from Nuget and received the error

Is it possible to take a screengrab of all the packages you have installed?

**Comment by MattH-Work** [comment]
No packages installed
Can't use Ultimate ( yet ) because of the WebView2Loader issue

Only thing I am installing is the AdvancedDataGridView
![2023-11-16_12h04_28](https://github.com/Krypton-Suite/Extended-Toolkit/assets/84494183/da5fc056-a0d7-47ed-95ba-d99f3e6b19e6)

**Comment by Wagnerp** [comment]
Not sure what's going on, as it only references the *.csproj file not a NuGet

![image](https://github.com/Krypton-Suite/Extended-Toolkit/assets/949607/2fe3398d-14a5-446d-acc9-b7090da0490c)

**Comment by Wagnerp** [comment]
@Smurf-IV 

Do we need to reinstate the 'Shared' packages?

**Comment by Wagnerp** [comment]
@MattH-Work 

I now know what's going on. The DLL **is not** packaged in the package. MS, why are you so stupid?

![image](https://github.com/Krypton-Suite/Extended-Toolkit/assets/949607/c3d20f09-b1f5-4d2a-b5e0-2031e0a44338)

**Comment by Wagnerp** [comment]
Will fix in the new `Ultimate` package

**Comment by Wagnerp** [comment]
Hi @MattH-Work 

Please retry using `Ultimate` build .320
