### ISSUE TITLE
Throwing exceptions using the Circularprogressbar control of The Ultimate 80.0 package during design

### ISSUE THREAD

**Issue by xxl-cc** [Krypton-Suite/Extended-Toolkit#446]
I used The Ultimate package and threw an exception when I placed the circularprogressbar in the winform: failed to load file or assembly WinFormAnimation_ DotNET, even if I manually add the missing reference, it won't work.

**Comment by Wagnerp** [comment]
Possibly need to uninstall the older packages for it to work.
