### ISSUE TITLE
nuget Packaging Issue

### ISSUE THREAD

**Issue by fraser125** [Krypton-Suite/Extended-Toolkit#5]
I'm using nuget from Visual Studio 2019
My project is .NET Framework 4.7.2
It's literally a New Project, no code or Forms have been modified.
I'm attempting to add all of the "Krypton.Toolkit.Suite.Extended.*" packages.
I am unable to add the "Krypton.Toolkit.Suite.Extended.Dialogs" package, the error is "Unable to resolve dependency 'Krypton.Toolkit.Suite.Extended.Palette.Controls'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'."

I think the reason for this error is that the package is called "Krypton.Toolkit.Suite.Extended.Palette.Controller" the difference being Controls and Controller. 
Thanks!

**Comment by herledant** [comment]
The next release should correct this.
Wagnerp tell me that he should build it friday.
I let him confirm.
