### ISSUE TITLE
[Bug]: Unable to load via nuget "Krypton.Toolkit.Suite.Extended.Dialogs" into a .net5.0 winform project

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Extended-Toolkit#52]
![image](https://user-images.githubusercontent.com/2418812/112330628-1cc90180-8cb0-11eb-9119-608d153cd520.png)

**Comment by Wagnerp** [comment]
A resolution would be to have the third party library in the codebase pointing at all supported frameworks. TBD 2107.

**Comment by Wagnerp** [comment]
Folded into V6
