### ISSUE TITLE
[Bug]: Readme.md documentation link is back to the same page

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Extended-Toolkit#64]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2418812/112846009-73ae4c80-909d-11eb-9c94-eb0ec4930068.png)

**Comment by Wagnerp** [comment]
Yes, going to update it to download the exe file when ready.

**Comment by Smurf-IV** [comment]
Or point to the stored `md` output ?

**Comment by Wagnerp** [comment]
Fixed as per v70
