### ISSUE TITLE
[Question]: Can the KryptonGrid be renamed and moved to the Standard-toolkit as it overrides the standard DataGridView?

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Extended-Toolkit#67]
The idea (As I see it) is that the Standard toolkit, is the representation of "Themed controls" of what is available as "Standard" from the Winform Controls in Visual Studio designer.

The "KryptonGrid" should be KryptonDataGridView as it overrides the Standard "DataGridView"

**Comment by Smurf-IV** [comment]
This could be done as a  step process
- Copy to Standard with the rename (ASAP)
- When V6 comes along remove from Extended and fix fallout.

**Comment by Smurf-IV** [comment]
Argghh...
But wait.. There is already a "KryptonDataGridView" in Standard, So what is the extended one doing ?
Why no comments in the `///` class to state what these things do ?

**Comment by Wagnerp** [comment]
Ahh it was from [this](https://github.com/ncarp/ExtendedRenderer) dead project.

**Comment by Smurf-IV** [comment]
So is it to be removed, or merged or something else ?
Without examples of usage these classes could be just cluttering the codebase, making the binary dll's big for no reason.

**Comment by Wagnerp** [comment]
Yes the control can be removed, as it appears to be this: https://github.com/ncarp/ExtendedRenderer/blob/master/KryptonGrid.cs

**Comment by Wagnerp** [comment]
Or moved into the standard toolkit?

**Comment by Smurf-IV** [comment]
`KryptonDataGridView` already exists in the Standard toolkit, and is a lot more complex and complete than `KryptonGrid`

**Comment by Smurf-IV** [comment]
> 
> 
> Yes the control can be removed, as it appears to be this: https://github.com/ncarp/ExtendedRenderer/tree/master/StdControls/GridView

Some of those controls "sound" interesting, and should be in the Ext kit as they are extensions to the grid, but need to be brought in line with the Standard grid view

This task could be part of the V6-next refactor to have a GridView only Extension dll (And I'll do it as part of the Master-Detail work ?)

**Comment by Wagnerp** [comment]
Those controls were bought over, as that project seems to be dead. The only control which I can't seem to get to work is the `ListView`, even though it is working in that project.

**Comment by Smurf-IV** [comment]
#135 created to cover the implementation work
