### ISSUE TITLE
[Other Issues]: Object.ListView should not really be part of this suite

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Extended-Toolkit#68]
The original source license is GNU GPL, and the author states that if this is used in closed source to contact him.
This is direct contrast to the BSD-3 that Krypton goes under (And is referenced in the license.md file under this project in KSET).
Also the Alpha code base does not build
Also, the part code base that is currently in alpha is old, as the author has updated in 2018 (And the code in KSET is only upto 2015)

https://sourceforge.net/p/objectlistview/code/HEAD/tree/cs/trunk/ObjectListView/

**Comment by Wagnerp** [comment]
It's because I chose not to develop it further, because:-

A) GNU License
B) The codebase was a complete mess

Will be removed as part of V6

**Comment by Smurf-IV** [comment]
Are V6 changes being done in Alpha (Canary) or do you want them done in the V6 next branch ?
i.e. is the V6 branch stable enough for 2 devs to work on together yet ?

**Comment by Wagnerp** [comment]
@Smurf-IV 

All v6 development is being done in the `version-next` branch. I've ripped out all code to start anew with a directory structure in line with the standard toolkit. So, yes it is stable to work on.

**Comment by Smurf-IV** [comment]
@Wagnerp Done in Alpha, canary, master
What are the other branches for ?

**Comment by Wagnerp** [comment]
@Smurf-IV They can all be removed, apart from `version-next` & `v6-pre-release` as they were testing branches. I'll undertake this task.
